version: '3.8'

services:
  web:
    image: faq4265/todo-list:latest
    container_name: web_asg2
    ports:
      - "8000:8000"   # original port
    environment:
      - MONGODB_URL=mongodb://mongodb_asg2:27017/
    volumes:
      - ./app:/app     # required change for Part-II
    depends_on:
      - mongodb
    networks:
      - todo_network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb_asg2
    ports:
      - "27017:27017"   # original port
    volumes:
      - mongodb_data_asg2:/data/db
    networks:
      - todo_network
    restart: always

networks:
  todo_network:
    driver: bridge

volumes:
  mongodb_data_asg2:
