FROM python:3.11

WORKDIR /app

# Copy the root requirements.txt
COPY requirements.txt ./requirements.txt

# Install all dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy your selenium-tests folder into the container
COPY selenium-tests/ ./selenium-tests

WORKDIR /app/selenium-tests

# Default command to run your tests
CMD ["python", "test_todo_app.py"]
